# Generated by Django 3.2 on 2023-10-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20231021_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ненужный пароль'),
        ),
    ]
