# Generated by Django 3.2 on 2023-10-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=None, verbose_name='Рейтинг произведения'),
        ),
    ]
