# Generated by Django 3.2 on 2023-10-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20231017_1039'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='authortitletogether',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review'),
        ),
    ]
