# Generated by Django 3.2 on 2023-10-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_titleimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleImport',
        ),
    ]
