# Generated by Django 3.2 on 2023-10-17 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0006_auto_20231017_2039'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_title_review',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
    ]
