# Generated by Django 3.2 on 2023-10-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20231017_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=None, verbose_name='Рейтинг произведения'),
        ),
    ]
