# Generated by Django 3.2 on 2023-10-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг произведения'),
        ),
    ]
